#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH --time=2-00:00:00
#SBATCH --qos=long
#SBATCH --partition=amilan
#SBATCH --job-name=wave_script_ww3
#SBATCH --output=wave_script_ww3_004.out

module purge
module load anaconda
conda activate xesmf_env

python3 wave_script_ww3.py
