#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=25
#SBATCH --time=02:00:00
#SBATCH --partition=amem
#SBATCH --qos=mem
#SBATCH --mem=400G
#SBATCH --job-name=HYCOM2ROMS_temp_bryclm_highmem
#SBATCH --output=HYCOM2ROMS_temp_bryclm_highmem_001.out

module purge
module load anaconda
conda activate xesmf_env

python3 HYCOM2ROMS_temp_bryclm.py
