#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=25
#SBATCH --time=03:00:00
#SBATCH --partition=amem
#SBATCH --qos=mem
#SBATCH --mem=400G
#SBATCH --job-name=manually_fix_nans_v_currents_clm
#SBATCH --output=manually_fix_nans_v_currents_clm_001.out

module purge
module load anaconda
conda activate xesmf_env

python3 manually_fix_nans_v_currents_clm.py
