#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=30
#SBATCH --time=08:00:00
#SBATCH --qos=normal
#SBATCH --partition=amilan
#SBATCH --job-name=plot_movie_plots
#SBATCH --output=plot_movie_plots_001.out
#SBATCH --account=ucb543_asc2

module purge
module load anaconda
conda activate xesmf_env

python3 plot_movie_plots.py
