#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=35
#SBATCH --time=02:00:00
#SBATCH --qos=normal
#SBATCH --partition=amilan
#SBATCH --job-name=time_avg_ssflux_ssc
#SBATCH --output=time_avg_ssflux_ssc_standard_avg1m_fromsurf_002.out

module purge
module load anaconda
conda activate xroms

python3 plot_time_avg_ssflux_ssc_masked_xy_2020.py
